iTwin/changed-elements-react

packages/changed-elements-react/package.json
packages/changed-elements-react/publish.yaml

* Use Node.js 18.x in the release pipeline
* `main` field in `package.json` was causing an extra `././lib/cjs/index.js` file to be included in the package (not a typo)
* Fix `"moduleResolution": "bundler"` setting being used during transpilation when it's not allowed for `CommonJS` modules

Fixup release process

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/widgets/ElementsList.tsx

AppUI has this bug where when you switch between widget tabs, widgets momentarily have zero height and thus browser becomes unable to restore scroll offset for widget content. This change implements a workaround for this issue by storing and restoring scroll offset manually.
* Refactor `ElementsList` into functional component
* Fix elements list scroll offset not being restored

Fix ElementsList scroll offset not being restored

---

packages/changed-elements-react/src/widgets/EnhancedElementsInspector.tsx

Also fix layout shift which happens during closing animation.
This change does not add an entry to `CHANGELOG.md` because these defects do not exist in `0.1.0` version.

Fix saved filters dialog not closing after clicking Cancel

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx
packages/changed-elements-react/src/widgets/EnhancedElementsInspector.tsx

This change was needed to make it possible for AppUI consumers to fix widget scroll offset failing to restore when switching between widget tabs.
Because consumers are now responsible to fix this AppUI bug themselves, previous changelog entry that mentions this fix has been removed.

Expose ElementsList ref through ChangedElementsWidget props

---

.gitignore
packages/test-app-backend/src/main.ts

This cache is supposed to be per-application, but the default cache location can potentially be shared by multiple iTwin.js applications.

Place cache directory within test-app-backend

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/common/ExpandableSearchBar/ExpandableSearchBar.scss
packages/changed-elements-react/src/common/ExpandableSearchBar/ExpandableSearchBar.tsx

* Reduce likelihood of style clashes for `ExpandableSearchBar` component.
* Replace outdated CSS variables in `ExpandableSearchBar` style rules.

Update ExpandableSearchBar CSS

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx

`ReportGeneratorDialog` obtains changed properties on component mount and this used to happen before a comparison is started. 
The fix is to mount the component conditionally when user presses the report generator button.

Fix report dialog not listing any changed properties

---

packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionEntries.tsx

Added Math.floor to Progress to get whole number progress

---

packages/changed-elements-react/src/index.ts
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/common/versionCompareToasts.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/common/versionCompareV2WidgetUtils.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareDialogProvider.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareSelectModal.tsx

… update call back and a toggle for toasts.

Added new props for v2 widget and dialog provider that allows for job update call back and a toggle for toasts

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/package.json

`0.4.0` and `0.5.0` changelogs got mixed up because two consecutive releases happened without ever doing the post-release step.

@itwin/changed-elements-react@0.5.0

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/package.json
packages/changed-elements-react/src/clients/iTwinApi.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareSelectModal.tsx

* Fixes comparison job error workflow in `VersionCompareSelectModal`. When error jobs are re-run, they delete the existing broken job and re-run a new job for the given job ID.

Updated comparison job error workflow.

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/api/VersionCompareManager.ts
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/AppUiVisualizationHandler.ts
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/VersionCompareFrontstageManager.ts

Also do not hide ChangedElementsWidget on comparison failure in the test app.

Cleanup after `startComparisonV2` failure

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/widgets/comparisonJobWidget/common/versionCompareV2WidgetUtils.ts

Fixes Changing to another version is not possible when version compare is already active

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/api/ChangedElementEntryCache.ts

We should have been doing a cache look-up. We passed an unloaded change elements entry, which was cached as loaded. So we would see the unloaded entry and return unloaded and try to load it. Then load it cache we loaded it. Then check if it was loaded and then get back unloaded bc we passed in an unloaded entry to check ...
Fixed by using cached value instead

Fixed infinite load that would occur with changed element entry look up

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/AutoSizer.tsx
packages/changed-elements-react/src/common.ts
packages/changed-elements-react/src/contentviews/PropertyComparisonTable.tsx
packages/changed-elements-react/src/widgets/ElementsList.tsx
packages/changed-elements-react/src/widgets/EnhancedElementsInspector.tsx
packages/changed-elements-react/src/widgets/InformationButton.tsx

* Fix the following console warnings in development environment
* Receiving invalid property when mounting `<ChangedElementsWidget />` with V2 version selector
* Receiving invalid list ref when displaying changed elements list
* `checked` checkbox property not being accompanied by `onChange` event handler when rendering element filters popup

Fix console warnings in development environment

---

packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/src/clients/iTwinApi.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/common/versionCompareToasts.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/common/versionCompareV2WidgetUtils.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareDialogProvider.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareSelectComponent.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareSelectModal.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareSelectorInner.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionEntries.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionList.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/hooks/useNamedVersionLoader.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/models/ComparisonJobModels.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/models/NamedVersions.ts
packages/changed-elements-react/src/widgets/comparisonJobWidget/models/VersionState.ts
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/AppUiVisualizationHandler.ts
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/PropertyComparisonFrontstage.tsx
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/PropertyComparisonTable.tsx
packages/test-app-frontend/src/App/ITwinJsApp/AppUi/VersionCompareFrontstageManager.ts
packages/test-app-frontend/src/App/ITwinJsApp/ITwinJsApp.tsx
packages/test-app-frontend/src/App/common/LoadingIndicator.tsx
packages/test-app-frontend/src/App/common/LoadingScreen.tsx
packages/test-app-frontend/src/main.tsx
packages/test-app-frontend/tsconfig.json
tsconfig.json

* Fix ES module imports not specifying script file extensions
* Modify `tsconfig.json` to enforce ES module resolution and detect missing file extensions in the future

Enforce use of ES modules

---

.github/workflows/CI.yaml

The only PRs the admin user creates are for releases and should not need the changeset status check.

Updated CI not to run changeset status if user is imodeljs-admin

---

.changeset/rare-peaches-double.md
.github/workflows/release-workflow.yml
package.json
packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/package.json

The build step failed in publishing, preventing the release. Now, the build is pointed to the correct directory and runs before release.
Reverted release PR changes.
Fixes :

Updated build pipeline with directed build

---

.changeset/rare-peaches-double.md
.github/workflows/release-workflow.yml
.npmrc
packages/changed-elements-react/CHANGELOG.md
packages/changed-elements-react/package.json

2025-01-21T16:43:36.0808631Z ##[group]Run changesets/action@v1
2025-01-21T16:43:36.0809056Z with:
2025-01-21T16:43:36.0809341Z   publish: pnpm changeset publish
2025-01-21T16:43:36.0809786Z   title: Release packages [publish docs]
2025-01-21T16:43:36.0810156Z   commit: Release packages [publish docs]
2025-01-21T16:43:36.0810514Z   createGithubReleases: true
2025-01-21T16:43:36.0810906Z   setupGitUser: true
2025-01-21T16:43:36.0832903Z env:
2025-01-21T16:43:36.0833286Z   PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
2025-01-21T16:43:36.0834228Z   GITHUB_TOKEN: ***
2025-01-21T16:43:36.0834924Z   NODE_AUTH_TOKEN: ***
2025-01-21T16:43:36.0835173Z   GIT_AUTHOR_NAME: imodeljs-admin
2025-01-21T16:43:36.0835487Z   GIT_AUTHOR_EMAIL: imodeljs-admin@users.noreply.github.com …

Updated .npmrc to fix following error

---

.changeset/breezy-cherries-compete.md
packages/changed-elements-react/src/NamedVersionSelector/NamedVersionSelector.css
packages/changed-elements-react/src/NamedVersionSelector/NamedVersionSelector.tsx
packages/changed-elements-react/src/index.ts
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx
packages/changed-elements-react/src/widgets/FeedbackButton.scss
packages/test-app-frontend/src/App/ITwinJsApp/ITwinJsApp.tsx
packages/test-app-frontend/src/environment.ts

List items were overlapping with each other:
Now, they are not, and added feedback button :

Fix for named version loader pane list item size and added feedback button

---

.changeset/thin-news-matter.md
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx
packages/changed-elements-react/src/widgets/comparisonJobWidget/components/VersionCompareDialogProvider.tsx

```
export type V2DialogProviderProps = {
children: React.ReactNode;
// Optional. When enabled will toast messages regarding job status. If not defined will default to false and will not show toasts.
enableComparisonJobUpdateToasts?: boolean;
/** On Job Update
* Optional. a call back function for handling job updates.
* @param comparisonJobUpdateType param for the type of update:
*  - "JobComplete" = invoked when job is completed
*  - "JobError" = invoked on job error
*  - "JobProcessing" = invoked on job is started
*  - "ComparisonVisualizationStarting" = invoked on when version compare visualization is starting
* @param toaster from iTwin Ui's useToaster hook. This is necessary for showing toast messages.
* @param jobAndNamedVersion param contain job and named version info to be passed …
```

Updated Params for onJobUpdate

---

.changeset/bright-cougars-bathe.md
packages/changed-elements-react/src/NamedVersionSelector/NamedVersionSelector.tsx
packages/changed-elements-react/src/api/VersionCompareManager.ts
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx

---
"@itwin/changed-elements-react": patch
---
-Fixes NamedVersionSelectorWidget showing loading and spinning forever when no named version present.
-Fixes default dialog being shown for NamedVersionSelectorWidget when a comparison is started. Now, we show the proper loading state with a spinner instead of "no comparison loaded."

Fixes NamedVersionSelectorWidget showing loading when no named version present and fixes default dialog being shown for new widget

---

.changeset/friendly-cats-occur.md
packages/changed-elements-react/public/locales/en/VersionCompare.json
packages/changed-elements-react/src/NamedVersionSelector/NamedVersionSelector.tsx
packages/changed-elements-react/src/NamedVersionSelector/TextEx.css
packages/changed-elements-react/src/api/VersionCompareManager.ts
packages/changed-elements-react/src/contentviews/PropertyComparisonTable.scss
packages/changed-elements-react/src/contentviews/PropertyComparisonTable.tsx
packages/changed-elements-react/src/widgets/ChangedElementsInspector.scss
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx

Font size, weight, and style:
Property comparison table coloring changes per row :
Updated colors for elements in tree (Squares) :
No more forever loading in the elements tree when backing out of property comparison :

UI updates for font weight font size font style, coloring and bug fixes

---

.changeset/three-stars-bake.md
packages/changed-elements-react/src/contentviews/PropertyComparisonTable.scss
packages/changed-elements-react/src/contentviews/PropertyComparisonTable.tsx

Fixed CSS for property-comparison-table-slider:
Before:
After :

Fixed css for property-comparison-table-slider

---

.changeset/big-bushes-repeat.md
packages/changed-elements-react/src/NamedVersionSelector/NamedVersionSelector.tsx
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx
packages/changed-elements-react/src/widgets/Documentation.scss
packages/changed-elements-react/src/widgets/Documentation.tsx
packages/changed-elements-react/src/widgets/InformationButton.tsx
packages/test-app-frontend/src/App/ITwinJsApp/ITwinJsApp.tsx

---
"@itwin/changed-elements-react": minor
---
- Added ability to add custom documentation link to information pane.
Pass href into top level widget as prop.

Info Button Docs Link Sub Component

---

.changeset/yummy-symbols-send.md
packages/changed-elements-react/src/widgets/EnhancedElementsInspector.tsx

#103 
Let me know if this is intentional to assign `path` to `searchpath`.
Feel like its just a minor typo. Looking at the code I think `searchpath` and `path` serves different purposes.

search message showing returning from version compare frontstage

---

.changeset/slimy-lines-heal.md
packages/changed-elements-react/src/widgets/ChangedElementsWidget.scss
packages/changed-elements-react/src/widgets/ChangedElementsWidget.tsx

JP mentioned this when i worked on the bug on right aligning header button that he want a bit more spacing between those buttons.
the side effect of this change is when squeezing it becomes
cuz of the fixed spacing
while previously if squeezed:

changedElementsHeaderButtons spacing

---

.changeset/many-flies-warn.md
packages/changed-elements-react/src/widgets/EnhancedElementsInspector.tsx

https://github.com/iTwin/changed-elements-react/pull/238
https://github.com/iTwin/changed-elements/issues/121
previous fix missed the condition on change being both property & indirect

advance filter bug fix
